-- Plik: workspace/Vanguard/Settings.lua

local Settings = {
	Version = "2.43.4",
	-- ESP
	ESP = false,
	Box = false,
	BoxType = "Full",
	Name = false,
	DistView = true,
	Health = false,
	HealthText = false,
	Weapon = false,
	Skel = false,
	Trace = false,
	Chams = false,
	ChamsRainbow = false,
	OffscreenArrows = false,
	OffscreenArrowHighVis = true,
	OffscreenArrowScale = 1.35,
	OffscreenArrowShowName = true,
	RenderBots = false,
	Team = false,
	ExcludeTeam = true,
	RealTeamColor = true,
	LoS = false,
	MaxDist = 500,
	Th = 1.5,
	V = Color3.fromRGB(0, 255, 150),
	O = Color3.fromRGB(255, 50, 50),

	-- AIM
	Aimbot = false,
	Silent = false,
	Trigger = false,
	TriggerKey = "V",
	TriggerMode = "Hold",
	TriggerDelay = 100,
	TriggerCompat = false,
	ShowTriggerHud = true,
	TriggerHudMinimal = true,
	VisibleCheck = true,
	ShowFOV = true,
	FOV = 80,
	Smooth = 0.4,
	AimCurve = true,
	TargetMode = "FOV",
	HitPart = "Head",
	AimBots = true,
	AimKey = "MouseButton2",
	SilentKey = "MouseButton1",

	-- RAGE
	MasterRage = false,
	AntiAim = false,
	AASpin = true,
	AASpinSpeed = 8,
	AAYaw = 0,
	AAPitch = 0,
	AAJitter = false,
	AAJitterRange = 45,
	RageBot = false,
	RageKey = "C",
	RageMode = "Toggle",
	RageDelay = 80,
	ShowRageHud = true,
	RageHudMinimal = true,
	RageHitPart = "Head",
	RageVisibleCheck = true,
	RageBots = true,
	RageMaxDist = 500,
	RageAimMode = "Silent",
	RageCompat = false,
	RageTrackSmooth = 0.35,

	-- WORLD
	FullBright = false,
	NoFog = false,
	WorldTimeLock = false,
	WorldTime = 14,
	WorldCustomLight = false,
	WorldColorHue = 0.55,
	WorldColorSat = 0.35,
	WorldLight = false,
	WorldBrightness = 2,
	WorldExposure = 0,
	WorldShadows = true,
	WorldAmbient = Color3.fromRGB(128, 128, 128),
	WorldOutdoorAmbient = Color3.fromRGB(128, 128, 128),
	WorldFog = false,
	WorldFogColor = Color3.fromRGB(192, 192, 192),
	WorldFogStart = 0,
	WorldFogEnd = 100000,
	WorldAtmoDensity = 0.3,
	WorldAtmoHaze = 0,
	WorldAtmoGlare = 0,
	WorldAtmoOffset = 0,
	WorldAtmoColor = Color3.fromRGB(199, 199, 199),
	WorldGrade = false,
	WorldCCBrightness = 0,
	WorldCCContrast = 0,
	WorldCCSaturation = 0,
	WorldCCTint = Color3.fromRGB(255, 255, 255),
	WorldColorShiftTop = Color3.fromRGB(255, 255, 255),
	WorldColorShiftBottom = Color3.fromRGB(255, 255, 255),
	WorldPost = false,
	WorldBloom = 0,
	WorldSunRays = 0,
	MenuBlur = true,
	MenuBlurSize = 18,

	-- INTERFACE
	MenuLang = "pl",
	NotifyStyle = "pro",

	-- MOVEMENT
	BHop = false,
	AutoStrafe = false,

	-- ANIMATIONS
	AnimSpeed = 1,
	AnimWeight = 1,
	AnimLoop = true,
	AnimPreferChat = true,
	AnimMovementPack = "",

	-- MUSIC (Internet Archive)
	MusicVolume = 0.65,
	MusicLoop = false,
	MusicSource = "audius",
	MusicLastQuery = "",
	ShowMusicWidget = true,
	MusicWidgetPosXScale = 0,
	MusicWidgetPosXOffset = 18,
	MusicWidgetPosYScale = 1,
	MusicWidgetPosYOffset = -90,
	MusicAutoQueue = true,

	-- HUD
	Crosshair = false,
	CrosshairStyle = "Dot",
	CrosshairColorMode = "Accent",
	CrosshairColor = Color3.fromRGB(255, 255, 255),
	CrosshairSize = 5,
	Spectators = false,
	Hitmarker = false,
	DamageLog = false,
	DamageNumbers = false,
	TargetInfo = false,
	Watermark = false,
	KeybindList = false,
	SessionStats = false,
	KillFeed = false,
	ShotTracers = false,
	KillShotTracers = true,
	HitSound = true,
	HitSoundVolume = 0.45,

	-- FRIENDS
	FriendClick = true,
	FriendIds = {},

	-- MISC
	HeadSize = false,
	HeadSizeScale = 2,
	HitboxSize = false,
	HitboxSizeScale = 1.5,
	MiscAffectFriends = false,
	MiscBots = true,
	AntiBypass = true,
	DebugAdonis = false,
	LogToFile = true,
	TransferScript = false,

	-- EFFECTS (local only)
	KillEffects = false,
	KillEffectStyle = "Neon",
	HitEffects = false,
	HitEffectStyle = "Lightning",
	SelfKillFX = false,

	-- UI runtime
	MenuOpen = false,
	LastShotAt = 0,
	LastShotHum = nil,
	LastShotChar = nil,
	LastShotPos = nil,
	LastShotRayOrigin = nil,
	LastShotRayDir = nil,
}

return Settings
