-- Plik: workspace/Vanguard/Settings.lua

local Settings = {
	Version = "2.52.74",
	-- ESP
	ESP = false,
	Box = false,
	BoxType = "Full",
	Name = false,
	ESPDisplayName = false,
	ESPTargetUserId = 0,
	DistView = true,
	Health = false,
	HealthText = false,
	Weapon = false,
	Skel = false,
	Trace = false,
	Chams = false,
	ChamsRainbow = false,
	OffscreenArrows = false,
	OffscreenArrowHighVis = true,
	OffscreenArrowScale = 1.35,
	OffscreenArrowShowName = true,
	RenderBots = false,
	Team = false,
	FriendsESP = false,
	FriendsESPSkipVisible = false,
	FriendBox = false,
	FriendHealth = false,
	FriendHealthText = false,
	FriendWeapon = false,
	FriendDistView = false,
	ExcludeTeam = true,
	RealTeamColor = true,
	LoS = false,
	MaxDist = 500,
	ESPRenderLimit = false,
	ESPRenderDist = 500,
	ESPRenderOnlyVisible = false,
	ESPLowerOpacityVisible = false,
	ESPLowerOpacityAmount = 55,
	LOSIgnoreSelf = true,
	Th = 1.5,
	V = Color3.fromRGB(0, 255, 150),
	O = Color3.fromRGB(255, 50, 50),
	F = Color3.fromRGB(170, 90, 255),
	T = Color3.fromRGB(255, 190, 40),

	-- AIM
	Aimbot = false,
	Silent = false,
	Trigger = false,
	TriggerKey = "V",
	TriggerMode = "Hold",
	TriggerDelay = 100,
	TriggerCompat = false,
	ShowTriggerHud = true,
	TriggerHudMinimal = true,
	VisibleCheck = true,
	ShowFOV = true,
	FOV = 80,
	Smooth = 0.4,
	AimCurve = true,
	TargetMode = "FOV",
	HitPart = "Head",
	AimBots = true,
	AimKey = "MouseButton2",
	SilentKey = "MouseButton1",

	-- RAGE
	MasterRage = false,
	AntiAim = false,
	AASpin = true,
	AASpinSpeed = 8,
	AAYaw = 0,
	AAPitch = 0,
	AAJitter = false,
	AAJitterRange = 45,
	RageBot = false,
	RageKey = "C",
	RageMode = "Toggle",
	RageDelay = 80,
	ShowRageHud = true,
	RageHudMinimal = true,
	RageHitPart = "Head",
	RageVisibleCheck = true,
	RageBots = true,
	RageMaxDist = 500,
	RageAimMode = "Silent",
	RageCompat = false,
	RageTrackSmooth = 0.35,

	-- WORLD
	FullBright = false,
	NoFog = false,
	WorldTimeLock = false,
	WorldTime = 14,
	WorldCustomLight = false,
	WorldColorHue = 0.55,
	WorldColorSat = 0.35,
	WorldLight = false,
	WorldBrightness = 2,
	WorldExposure = 0,
	WorldShadows = true,
	WorldAmbient = Color3.fromRGB(128, 128, 128),
	WorldOutdoorAmbient = Color3.fromRGB(128, 128, 128),
	WorldFog = false,
	WorldFogColor = Color3.fromRGB(192, 192, 192),
	WorldFogStart = 0,
	WorldFogEnd = 100000,
	WorldAtmoDensity = 0.3,
	WorldAtmoHaze = 0,
	WorldAtmoGlare = 0,
	WorldAtmoOffset = 0,
	WorldAtmoColor = Color3.fromRGB(199, 199, 199),
	WorldGrade = false,
	WorldCCBrightness = 0,
	WorldCCContrast = 0,
	WorldCCSaturation = 0,
	WorldCCTint = Color3.fromRGB(255, 255, 255),
	WorldColorShiftTop = Color3.fromRGB(255, 255, 255),
	WorldColorShiftBottom = Color3.fromRGB(255, 255, 255),
	WorldPost = false,
	WorldBloom = 0,
	WorldSunRays = 0,
	MenuBlur = true,
	MenuBlurSize = 18,

	-- INTERFACE
	MenuLang = "pl",
	NotifyStyle = "pro",

	-- MOVEMENT
	BHop = false,
	AutoStrafe = false,
	Speed = false,
	SpeedValue = 25,
	JumpPower = false,
	JumpPowerValue = 50,
	Fly = false,
	FlySpeed = 40,
	FlyKey = "E",
	-- Client-local Truss climb (Minecraft spider-like). Not noclip / not fly BV.
	Spider = false,
	SpiderSpeed = 14,
	SpiderStealth = true,
	SpiderBurstHeight = 7,
	SpiderCooldown = 1.4,
	Noclip = false,
	InfStamina = false,
	NoFallDmg = false,
	-- R6 anim-desync invis (local ghost + "YOU ARE VISIBLE" when airborne)
	Invisibility = false,
	InvisShowWarning = true,
	InvisWalkSpeed = 12,
	InvisKey = "X",

	-- ANIMATIONS
	AnimSpeed = 1,
	AnimWeight = 1,
	AnimLoop = true,
	AnimPreferChat = true,
	AnimMovementPack = "",

	-- MUSIC (Internet Archive)
	MusicVolume = 0.65,
	MusicLoop = false,
	MusicSource = "audius",
	MusicLastQuery = "",
	ShowMusicWidget = true,
	MusicWidgetPosXScale = 0,
	MusicWidgetPosXOffset = 18,
	MusicWidgetPosYScale = 1,
	MusicWidgetPosYOffset = -90,
	MusicAutoQueue = true,

	-- HUD
	Crosshair = false,
	CrosshairStyle = "Dot",
	CrosshairColorMode = "Accent",
	CrosshairColor = Color3.fromRGB(255, 255, 255),
	CrosshairSize = 5,
	Spectators = false,
	Hitmarker = false,
	DamageLog = false,
	DamageNumbers = false,
	TargetInfo = false,
	Watermark = false,
	KeybindList = false,
	SessionStats = false,
	KillFeed = false,
	ShotTracers = false,
	KillShotTracers = true,
	HitSound = true,
	HitSoundVolume = 0.45,

	-- FRIENDS
	FriendClick = true,
	FriendIds = {},

	-- CRIMINALITY (only active when game.GameId == 1494262959)
	CrimNoFall = false,
	CrimNoSpike = false,
	CrimNoRagdoll = false,
	CrimMeleeAura = false,
	CrimMeleeRange = 5,
	CrimWallbangTargetUserId = 0,
	CrimWallbangTargetName = "",
	CrimWallbangLive = false,
	CrimWallbangPickMode = "Both",
	CrimWallbangRefreshKey = "V",
	CrimWallbangPickKey = "None",
	CrimSafeESP = false,
	CrimSafeShowBroken = false,
	CrimSafeColor = Color3.fromRGB(255, 220, 50),
	-- Visual path only (no autofarm walk)
	CrimPathDisplay = false,
	CrimPathTarget = "Safe",
	CrimPathMaxDist = 350,
	CrimPathRefresh = 0.55,
	CrimPathColor = Color3.fromRGB(80, 200, 255),
	CrimPathJumpColor = Color3.fromRGB(255, 170, 40),
	CrimPathEndColor = Color3.fromRGB(90, 255, 140),
	CrimPathStatus = "",
	CrimPathCrateBasic = true,
	CrimPathCrateRare = true,
	CrimPathFullOnly = false,
	CrimDealerESP = false,
	CrimDealerColor = Color3.fromRGB(100, 200, 255),
	CrimRebelDealerColor = Color3.fromRGB(255, 90, 70),
	CrimCrateESP = false,
	CrimCrateBasic = true,
	CrimCrateRare = true,
	CrimCrateColor = Color3.fromRGB(255, 190, 60),
	CrimCrateRareColor = Color3.fromRGB(255, 55, 55),
	CrimCrateMaxDist = 400,
	CrimCratePickup = false,
	CrimCratePickupBasic = true,
	CrimCratePickupRare = true,
	CrimCratePickupDist = 3.5,
	CrimCratePickupDelay = 200,
	CrimCratePickupFx = true,
	CrimBountyTracker = false,
	CrimESPMaxDist = 300,
	CrimAimPrediction = false,
	CrimAimPredictionLead = 12,
	CrimNoRecoil = false,
	CrimNoSpread = false,
	CrimQuickEquip = false,
	CrimAutoReload = false,
	CrimAutoRespawn = false,
	CrimStaffDetect = false,
	CrimRemoveSmokeExplosion = false,
	CrimNoFailLockpick = false,
	CrimAutoOpenDoors = false,
	CrimAutoUnlockDoors = false,
	CrimRemoteElevator = false,
	CrimRemoteElevatorKey = "T",
	CrimRemoteElevatorMaxDist = 400,
	CrimInfStamina = false,
	CrimFullBright = false,
	CrimMenuMusic = false,
	CrimMenuMusicTrack = "PolskiePola",
	CrimHitSoundSwap = false,
	CrimHitSoundPreset = "UT",
	CrimHitSoundCooldown = 180, -- ms between headshot SFX (P90 spray)
	CrimMoneyPickup = false,
	CrimMoneyPickupDist = 5,
	CrimMoneyPickupDelay = 1000,
	CrimAllowanceClaim = false,
	CrimAllowanceClaimDist = 12,
	CrimAllowanceClaimDelay = 3000,
	CrimFastPickup = false,
	CrimFastPickupGuns = true,
	CrimFastPickupMelee = true,
	CrimFastPickupArmor = true,
	CrimFastPickupRange = 6,
	CrimGunESP = false,
	CrimGunESPGuns = true,
	CrimGunESPMelee = true,
	CrimGunESPMaxDist = 250,
	CrimGunESPGunColor = Color3.fromRGB(80, 255, 140),
	CrimGunESPMeleeColor = Color3.fromRGB(255, 170, 60),

	-- MISC
	HeadSize = false,
	HeadSizeScale = 2,
	HitboxSize = false,
	HitboxSizeScale = 1.5,
	MiscAffectFriends = false,
	MiscBots = true,
	AntiBypass = true,
	DebugAdonis = false,
	LogToFile = true,
	TransferScript = false,

	-- EFFECTS (local only)
	KillEffects = false,
	KillEffectStyle = "Neon",
	HitEffects = false,
	HitEffectStyle = "Lightning",
	SelfKillFX = false,

	-- UI runtime
	MenuOpen = false,
	LastShotAt = 0,
	LastShotHum = nil,
	LastShotChar = nil,
	LastShotPos = nil,
	LastShotRayOrigin = nil,
	LastShotRayDir = nil,
}

return Settings
